### ISSUE TITLE
Problem updating device type

### ISSUE THREAD

**Issue by sangorrin** [Linaro/lava-server#11]
I tried to update my device-type but got some errors on 2017.7.

\# lava-server manage device-types update renesas-iwg20m
Traceback (most recent call last):
  File "/usr/bin/lava-server", line 78, in <module>
    main()
  File "/usr/bin/lava-server", line 74, in main
    execute_from_command_line(django_options)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/dist-packages/lava_server/management/commands/device-types.py", line 110, in handle
    self.handle_update(options['device-type'], options['alias'])
  File "/usr/lib/python2.7/dist-packages/lava_server/management/commands/device-types.py", line 122, in handle_update
    dt.aliases.add(alias_item)
UnboundLocalError: local variable 'alias_item' referenced before assignment

The alias is supposed to be optional according to the help that comes out when you
execute 'lava-server manage device-types update'.

The problem seems to be in mainstream as well.
https://github.com/Linaro/lava-server/blob/release/lava_server/management/commands/device-types.py

    def handle_update(self, device_type, alias):
        """Update an existing device type"""
        try:
            dt = device_type = DeviceType.objects.get(name=device_type)
        except DeviceType.DoesNotExist:
            raise CommandError("Unable to find device-type '%s'" % device_type)
        if alias:
            alias_item, _ = Alias.objects.get_or_create(name=alias)
        dt.aliases.add(alias_item) <-- **THIS LINE SHOULD BE INDENTED UNDER "IF ALIAS"**

**Comment by ghost** [comment]
The only thing update does is assign an alias, so if no alias is specified, there is nothing to do. So your solution is the wrong one. Instead, if alias is None, the function should raise an error. --alias is not optional for update, so that needs a change too.
In future, please always check with the latest released version (2017.9) too. This fix will go into 2017.10 via https://review.linaro.org/21391

**Comment by sangorrin** [comment]
Thanks, very fast! :O
So for updating the device-type, I just have to overwrite the old version in the corresponding /etc/lava-server/... folder?

**Comment by ghost** [comment]
Do you mean updating the Jinja2 template? Yes, modifying the jinja2 is a filesystem operation. All the lava-server manage commands simply work on the database objects.
